platform :ios, '11.0'

use_frameworks!
inhibit_all_warnings!

target 'ReactNativeCore_Example' do
  
  pod 'react-ios', path: '../'
  pod 'react-component', '~> 1.2.0'
#  pod 'react-expo', '~> 1.1.0'
  
  target 'ReactNativeCore_Tests' do
    inherit! :search_paths
    
  end
end
